CODE_ROOT: ./app
API_PORT: 8000
LOG_DIR: ./logs
LOG_MONITOR_INTERVAL: 60
MODELS:
  default:
    name: deepseek/deepseek-r1-0528:free
    api_key: ${OPENROUTER_API_KEY}
    url: https://openrouter.ai/api/v1/chat/completions
# E-mail para notificações (opcional)
NOTIFY_EMAIL: ''
# Caminho opcional para um modelo local da HuggingFace
LOCAL_MODEL: ''
COMPLEXITY_HISTORY: complexity_history.json
START_MODE: fast  # options: fast, full, custom
START_TASKS: []  # aplica apenas se START_MODE = custom (scan, watch, monitor)
RESCAN_INTERVAL_MINUTES: 15
MODEL_TIMEOUT: 60  # Tempo máximo de espera por resposta da IA (em segundos)
SHOW_REASONING_BY_DEFAULT: false
SHOW_CONTEXT_BUTTON: false
ENABLE_AI_SUMMARY: false
TESTS_USE_ISOLATION: true
TEST_CPU_LIMIT: 1
TEST_MEMORY_LIMIT_MB: 512
LEARNING_RATE_LIMIT: 5


AUTO_MONITOR_FAILURES: 3
AUTO_MONITOR_FILES: 5
AUTO_MONITOR_HOURS: 72
RLHF_THRESHOLD: 10
RLHF_OUTPUT_DIR: ./logs/rlhf_results
