CODE_ROOT: ./app
API_PORT: 8000
LOG_DIR: ./logs
LOG_MONITOR_INTERVAL: 60
ERROR_LOG_PATH: errors_log.jsonl
ERROR_LOG_MAX_LINES: 1000
MODELS:
  default:
    name: deepseek/deepseek-r1-0528:free
    api_key: ${OPENROUTER_API_KEY}
    url: https://openrouter.ai/api/v1/chat/completions
# E-mail para notificações (opcional)
NOTIFY_EMAIL: ''
# Webhook Slack para notificações (opcional)
NOTIFY_SLACK: ''
# Caminho opcional para um modelo local da HuggingFace
LOCAL_MODEL: ''
COMPLEXITY_HISTORY: complexity_history.json
COMPLEXITY_TAG_THRESHOLD: 10
AUTO_REVIEW_COMPLEXITY_THRESHOLD: 10
START_MODE: fast  # options: fast, full, custom
START_TASKS: []  # aplica apenas se START_MODE = custom (scan, watch, monitor)
RESCAN_INTERVAL_MINUTES: 15
MODEL_TIMEOUT: 60  # Tempo máximo de espera por resposta da IA (em segundos)
SHOW_REASONING_BY_DEFAULT: false
SHOW_CONTEXT_BUTTON: false
ENABLE_AI_SUMMARY: false
TESTS_USE_ISOLATION: true
TEST_CPU_LIMIT: 1
TEST_MEMORY_LIMIT_MB: 512
LEARNING_RATE_LIMIT: 5


AUTO_MONITOR_FAILURES: 3
AUTO_MONITOR_FILES: 5
AUTO_MONITOR_HOURS: 72
RLHF_THRESHOLD: 10
RLHF_OUTPUT_DIR: ./logs/rlhf_results
SANDBOX_IMAGE: python:3.10-slim
SANDBOX_CPUS: "1"
SANDBOX_MEMORY: 512m
SANDBOX_NETWORK: bridge        # or "host"
SANDBOX_ALLOWED_HOSTS:
  - huggingface.co
MAX_PROMPT_TOKENS: 1000
APPROVAL_MODE: suggest
DIFF_STYLE: inline  # options: inline, side_by_side
AUTO_APPROVAL_RULES:
  - action: edit
    path: "docs/**"
    approve: true
