name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          grep -vE '^(tensorflow|sentence-transformers|transformers|spacy|torch|tensorflow-gpu|apache-airflow|mlflow|optuna|selenium)' requirements.txt > req.txt
          pip install -r req.txt
          pip install pytest
          pip install 'dvc[s3]'
      - name: Pull DVC data
        run: dvc pull
      - name: Run tests
        run: pytest
      - name: Push DVC data
        if: always()
        run: dvc push
