apiVersion: apps/v1
kind: Deployment
metadata:
  name: dask-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dask-scheduler
  template:
    metadata:
      labels:
        app: dask-scheduler
    spec:
      containers:
      - name: scheduler
        image: daskdev/dask:latest
        args: ["dask-scheduler"]
        ports:
        - containerPort: 8786
