name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8 bandit coverage mypy pylint
      - name: Lint
        run: flake8 devai
      - name: Security
        run: bandit -r devai
      - name: Type check
        run: mypy devai
      - name: Lint Pylint
        run: pylint devai || true
      - name: Test
        run: pytest -q
      - name: Coverage
        run: coverage run -m pytest -q && coverage report
